### ISSUE TITLE
Unable to download

### ISSUE THREAD

**Issue by DavidGarciaCat** [enrich-data/enrich-api-php#1]
Hey there,

On the [Usage](https://github.com/enrich-data/enrich-api-php#usage) section of your `README.md` file it says:
```
Install the library with Composer.
```

However your package `enrich-data/enrich-api-php` (as named on your `composer.json` file) is not included as part of Packagist, meaning that composer won't be able to look for it and download a copy, because Packagist is the official repository for composer.

Can you please consider to [submit the Git URL](https://packagist.org/packages/submit) and set-up the repository to get the latest updates when a a new release is tagged?

Thanks,

**Comment by valeriansaliou** [comment]
Hi! Thank you, the package is now good to go with Packagist: https://packagist.org/packages/enrich-data/enrich-api-php
